# This image is a base for the console client, with maven and the project dependencies
# stored into the image maven repository, so that recompilation of the project with
# the console client dockerfile doesn't take an eternity.
# This image is to be rebuilt only when dependencies change across the projects.
FROM maven:3.6.0-jdk-11-slim

ADD . /tmp/project

RUN cd /tmp/project && \
    mvn package -Dmaven.test.skip=true && \
    cd .. && rm -rf project