#
# 4X Framework - A framework to develop turn based strategy games
# Copyright © 2018 Loïc Prieto Dehennault (loic.sephiroth@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This image is a base for the console client, with maven and the project dependencies
# stored into the image maven repository, so that recompilation of the project with
# the console client dockerfile doesn't take an eternity.
# This image is to be rebuilt only when dependencies change across the projects.
FROM maven:3.6.0-jdk-11-slim

ADD . /tmp/project

RUN cd /tmp/project && \
    mvn package -Dmaven.test.skip=true && \
    cd .. && rm -rf project